Rama a
VitmiTor/tareasiete pull request #1
Opened 2022-09-24 21:52 UTC by VitmiTor

Entrega de tarea 7

2022-09-24 22:01 UTC, calvarioTeacher31 requested changes

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/test/java/excelReader/PokemonTests.java
> +    @Test(groups = {smoke}, dataProvider = pokemon1DataProvider, dataProviderClass = DataProviders.class)
esto va al regression

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/test/java/excelReader/PokemonTests.java
> +        softAssert.assertTrue(pokemon.getAtk() > 0, "El ataque es mayor a 0");
los mensajes los dejaríá con algo máßs corto como ataque, defensa, etc

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/test/java/jsonReader/PersonaTests.java
> +        var personaJson = dataProviders.getPersona();
ya no sería personaJson ya que ya es una clase solo sería persona

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/test/java/excelReader/PokemonTests.java
> +
linea 16 está por las puras

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/main/java/utilities/DataProviders.java
> +
línea 15 o 16 por las puras

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/main/java/utilities/DataProviders.java
> +    private Logs log = new Logs();
logs puede ser final ya que no cambia

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/main/java/models/Pokemon.java
> +
línea 26 por las puras

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/main/java/models/MaestroPokemonModel.java
> +    private int numMax = 20;
estos no cambian deben ser final

2022-09-24 22:01 UTC, calvarioTeacher31 commented on src/main/java/base/BaseTest.java
> +        excelReader = new ExcelReader();
excel reader puede ir en la misma línea 15 no es necesario inicializarlo acá

2022-09-25 16:18 UTC, calvarioTeacher31 requested changes

2022-09-25 16:18 UTC, calvarioTeacher31 commented on src/main/java/models/Pokemon.java
> +
falta la anotación excel Sheet, ahora te funciona porque solo tienes un tab pero cuando tengas varios se va a caer

2022-09-25 16:18 UTC, calvarioTeacher31 commented on src/main/java/utilities/JsonReader.java
> +
línea 22 por las puras

2022-09-25 16:18 UTC, calvarioTeacher31 commented on src/test/resources/suites/suite.xml
> +<?xml version="1.0" encoding="UTF-8"?>
este file debe llamarse smoke.xml

2022-09-25 16:18 UTC, calvarioTeacher31 commented on src/test/java/excelReader/PokemonTests.java
> +    private List<Pokemon> pokemonList;
esta variable para qué sirve? si no sirve entonces borrarla

2022-09-25 16:24 UTC, VitmiTor commented on src/main/java/models/Pokemon.java
> +
ok resuelto

2022-09-25 16:25 UTC, VitmiTor commented on src/main/java/utilities/JsonReader.java
> +
ok resuelto

2022-09-25 16:26 UTC, VitmiTor commented on src/test/resources/suites/suite.xml
> +<?xml version="1.0" encoding="UTF-8"?>
ok resuelto

2022-09-25 16:26 UTC, VitmiTor commented on src/test/java/excelReader/PokemonTests.java
> +    private List<Pokemon> pokemonList;
ok se borra

2022-09-25 17:22 UTC, calvarioTeacher31 approved these changes

2022-09-25 17:23 UTC, merged